CREATE TABLE "users" (
  "user_id" uuid PRIMARY KEY,
  "first_name" varchar(100),
  "last_name" varchar(100),
  "email" varchar(255) UNIQUE,
  "area_id" int,
  "created_at" timestamp
);

CREATE TABLE "areas" (
  "area_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "latitude" "DECIMAL(9,6)",
  "longitude" "DECIMAL(9,6)"
);

CREATE TABLE "candidates" (
  "candidate_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "area_id" int
);

CREATE TABLE "votes" (
  "vote_id" uuid PRIMARY KEY,
  "user_id" uuid UNIQUE,
  "candidate_id" int,
  "area_id" int,
  "vote_time" timestamp,
  "is_valid" boolean
);

CREATE TABLE detected_anomalies (
  "anomaly_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vote_id" uuid,
  "user_id" uuid UNIQUE,
  "candidate_id" int,
  "vote_area_id" int,
  "user_area_id" int,
  "vote_time" timestamp,
  "anomaly" boolean,
  "anomaly_score" float
);

create table analyzed_anomalies(
  "anomaly_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vote_id" VARCHAR(255),
  "user_id" VARCHAR(255),
  "candidate_id" int,
  "vote_area_id" int,
  "user_area_id" int,
  "vote_time" timestamp,
  "anomaly" boolean,
  "anomaly_score" float
)

create table results(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	candidate_id int,
  name varchar(100),
	total_votes int,
  position int,
	area_id int
)

ALTER TABLE "users" ADD FOREIGN KEY ("area_id") REFERENCES "areas" ("area_id");

ALTER TABLE "candidates" ADD FOREIGN KEY ("area_id") REFERENCES "areas" ("area_id");

ALTER TABLE "votes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "votes" ADD FOREIGN KEY ("candidate_id") REFERENCES "candidates" ("candidate_id");

ALTER TABLE "votes" ADD FOREIGN KEY ("area_id") REFERENCES "areas" ("area_id");

ALTER TABLE "anomalies" ADD FOREIGN KEY ("vote_id") REFERENCES "votes" ("vote_id");

ALTER TABLE votingsystem.analyzed_anomalies ADD FOREIGN KEY ("vote_id") REFERENCES votingsystem.votes ("vote_id");

ALTER TABLE votingsystem.analyzed_anomalies ADD FOREIGN KEY ("candidate_id") REFERENCES votingsystem.candidates ("candidate_id");

ALTER TABLE votingsystem.analyzed_anomalies ADD FOREIGN KEY ("area_id") REFERENCES votingsystem.areas ("area_id");

ALTER TABLE votingsystem.results ADD FOREIGN KEY ("candidate_id") REFERENCES votingsystem.candidates ("candidate_id");

ALTER TABLE votingsystem.results ADD FOREIGN KEY ("area_id") REFERENCES votingsystem.areas ("area_id");

ALTER TABLE votingsystem.anomalies RENAME TO detected_anomalies;