CREATE TABLE "users" (
  "user_id" uuid PRIMARY KEY,
  "first_name" varchar(100),
  "last_name" varchar(100),
  "email" varchar(255) UNIQUE,
  "area_id" int,
  "created_at" timestamp
);

CREATE TABLE "areas" (
  "area_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "latitude" "DECIMAL(9,6)",
  "longitude" "DECIMAL(9,6)"
);

CREATE TABLE "candidates" (
  "candidate_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "area_id" int
);

CREATE TABLE "votes" (
  "vote_id" uuid PRIMARY KEY,
  "user_id" uuid UNIQUE,
  "candidate_id" int,
  "area_id" int,
  "vote_time" timestamp,
  "is_valid" boolean
);

CREATE TABLE "anomalies" (
  "anomaly_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vote_id" uuid,
  "anomaly_type" varchar(100),
  "confidence" float,
  "detected_at" timestamp
);

ALTER TABLE "users" ADD FOREIGN KEY ("area_id") REFERENCES "areas" ("area_id");

ALTER TABLE "candidates" ADD FOREIGN KEY ("area_id") REFERENCES "areas" ("area_id");

ALTER TABLE "votes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "votes" ADD FOREIGN KEY ("candidate_id") REFERENCES "candidates" ("candidate_id");

ALTER TABLE "votes" ADD FOREIGN KEY ("area_id") REFERENCES "areas" ("area_id");

ALTER TABLE "anomalies" ADD FOREIGN KEY ("vote_id") REFERENCES "votes" ("vote_id");
